### ISSUE TITLE
Fatal errors raised when run in production mode at request time

### ISSUE THREAD

**Issue by eckdanny-osi** [ca-cwds/case-management#158]
Steps to Reproduce:

Build Assets:

```sh
RAILS_ENV=production NODE_ENV=production rails assets:precompile
```

Run in production mode:

```sh
SECRET_KEY_BASE=MY_SECRET RAILS_ENV=production NODE_ENV=production rails server
```

so far so good. Now open http://localhost:3000 and check `log/production.log`:

```
I, [2018-01-15T20:10:18.314938 #42965]  INFO -- : [c6e2bb29-1faa-479c-9212-bbca8af3995e] Started GET "/" for 127.0.0.1 at 2018-01-15 20:10:18 -0800
F, [2018-01-15T20:10:18.315714 #42965] FATAL -- : [c6e2bb29-1faa-479c-9212-bbca8af3995e]   
F, [2018-01-15T20:10:18.319296 #42965] FATAL -- : [c6e2bb29-1faa-479c-9212-bbca8af3995e] NameError (uninitialized constant Infrastructure::CwdsAuthenticator::SecurityPolicy
Did you mean?  SecurityError):
F, [2018-01-15T20:10:18.319340 #42965] FATAL -- : [c6e2bb29-1faa-479c-9212-bbca8af3995e]   
F, [2018-01-15T20:10:18.319365 #42965] FATAL -- : [c6e2bb29-1faa-479c-9212-bbca8af3995e] lib/infrastructure/cwds_authenticator.rb:12:in `call'
I, [2018-01-15T20:10:18.503950 #42965]  INFO -- : [9732bec6-5918-41a6-8ddc-28ea69083fdb] Started GET "/favicon.ico" for 127.0.0.1 at 2018-01-15 20:10:18 -0800
F, [2018-01-15T20:10:18.504277 #42965] FATAL -- : [9732bec6-5918-41a6-8ddc-28ea69083fdb]   
F, [2018-01-15T20:10:18.507262 #42965] FATAL -- : [9732bec6-5918-41a6-8ddc-28ea69083fdb] NameError (uninitialized constant Infrastructure::CwdsAuthenticator::SecurityPolicy
Did you mean?  SecurityError):
F, [2018-01-15T20:10:18.507322 #42965] FATAL -- : [9732bec6-5918-41a6-8ddc-28ea69083fdb]   
F, [2018-01-15T20:10:18.507353 #42965] FATAL -- : [9732bec6-5918-41a6-8ddc-28ea69083fdb] lib/infrastructure/cwds_authenticator.rb:12:in `call'
```

**Comment by eckdanny-osi** [comment]
Is this an `autoload_paths` or `eager_load_paths` thing?
